#/Users/hachangjin/IdeaProjects/todo-service
server:
  port: 10005
  tomcat:
    accesslog:
      directory: /Users/hachangjin/IdeaProjects/todo-service/tomcatLogs
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 14
      pattern: '%h %l %u %t "%r" %s %b %D'
      prefix: test_access
      rotate: true
      suffix: .log
    basedir: /Users/hachangjin/IdeaProjects/todo-service/tomcatLogs